name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rentcamp:latest

      - name: Connect SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker stop ${{ secrets.CONTAINER_NAME }} 
            sudo docker rm ${{ secrets.CONTAINER_NAME }} 
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/rentcamp 
            sudo docker run --name ${{ secrets.CONTAINER_NAME }} -p 8080:8080 -d \
              -e DBHOST=${{secrets.DBHOST}} \
              -e DBPORT=${{secrets.DBPORT}} \
              -e DBNAME=${{secrets.DBNAME}} \
              -e DBUSER=${{secrets.DBUSER}} \
              -e DBPASSWORD=${{secrets.DBPASSWORD}} \
              -e SECRET=${{secrets.SECRET}} \
              -e RefreshSecret=${{secrets.REFSECRET}} \
              -e CDN_Cloud_Name=${{secrets.DBHOST}} \
              -e CDN_API_Key=${{secrets.CDN_API_Key}} \
              -e CDN_API_Secret=${{secrets.CDN_API_Secret}} \
              -e CDN_Folder_Name=${{secrets.CDN_Folder_Name}} \
              ${{ secrets.DOCKERHUB_USERNAME }}/alhadji2023
